### ISSUE TITLE
Support monochromator based plate readers in platereader_configuration.json

### ISSUE THREAD

**Issue by pleaderlee** [SD2E/platereader-etl-specs#1]
the current `platereader_configuration.json` doesn't have a great example for handling monochromator based plate readers.

we're using the Tecan Infinite m200 Pro with the following specs

```
The bandwidth of the Infinite M200 PRO  monochromator system 
is < 9 nm for wavelengths > 315 nm
and < 5 nm for wavelengths ≤ 315 nm.
```

**Comment by jakebeal** [comment]
Could you please expand on what you see as a problem? Presumably when you are picking a particular planned set of measurements (e.g., for OD), you will pick one particular wavelength to center the monochomator on to use as the excitation wavelength? Or what am I misunderstanding here?

**Comment by pleaderlee** [comment]
Just for clarification, is the platereader_configuration.json an experiment-centric specification of capability or a device-centric specification?

**Comment by jakebeal** [comment]
Not exactly either.  It is a specification of the collection of different ways to expect the instrument to be used in experiments --- i.e., the collection of excitation/emission relationships that may be used in a family of experiments that one wants to be comparable.

**Comment by pleaderlee** [comment]
sounds good. we'll put up a first draft and if new specifications are needed can add them in later drafts
